apiVersion: v1
kind: ConfigMap
metadata:
  name: swap-marketplace-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "swapmarket"
---
apiVersion: v1
kind: Secret
metadata:
  name: swap-marketplace-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  JWT_SECRET: "change-this-to-a-long-random-secret-32-bytes-minimum"
  RAZORPAY_KEY_ID: "rzp_test_replace_me"
  RAZORPAY_KEY_SECRET: "replace_me"
  RAZORPAY_WEBHOOK_SECRET: "replace_me"
